blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Feature Requests & Questions 
    url: https://github.com/abereghici/remix-themes/discussions
    about: Please ask and answer questions here.
  - name: ğŸ’¬ Remix Discord Channel 
    url: https://rmx.as/discord
    about: Please ask and answer questions here.